### ISSUE TITLE
[BUG] 长时间未登录后 token 未自动更新？

### ISSUE THREAD

**Issue by GoForceX** [GoForceX/PrescoreFlutter#8]
![Screenshot_2024-03-24-11-36-22-24_cf75b8a6cbe4709a607de562f9625318.jpg](https://github.com/GoForceX/PrescoreFlutter/assets/67143590/9ce05e83-d658-4cd1-9e01-6dbafca48789)

![Screenshot_2024-03-24-11-36-24-07_cf75b8a6cbe4709a607de562f9625318.jpg](https://github.com/GoForceX/PrescoreFlutter/assets/67143590/8c100741-565a-407e-9b5f-d4db96565ca7)

**Comment by GoForceX** [comment]
> 重启后是不是退出登录了。通过改密码模拟了一下token失效，应该是会自动更新的啊。

感觉这个还是比较随机，时有时无，下次如果碰巧遇见了的话传一个 log 在这里好了。

**Comment by GoForceX** [comment]
Fixed in f28d96e9c4b26f80d709c43a4dc9b8cc969f64a4

但是启动的时候会跳一个 “未登录” 的 SnackBar 😢

**Comment by GoForceX** [comment]
![图片](https://github.com/GoForceX/PrescoreFlutter/assets/67143590/2aa25e79-e9ca-4445-a91c-e83c9bc96388)

我这通过如下操作可稳定复现：

1. 打开软件并停留一段时间
2. 通过 **返回** 退出软件
3. 再次打开软件

**Comment by GoForceX** [comment]
测试了一下 89f847dc8c33572924a7d61edb6ba942c8d45713

倒是不会死循环了，但是第一次启动还是会有“未登录”

很怪

**Comment by GoForceX** [comment]
感觉这个如果短期内能修好的话，修好之后就可以发版了（ 🤔

**Comment by GoForceX** [comment]
重装了一下 App，现在我这也没法复现了，很怪异

但是后台有个 Error 不知道是否有关：

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(error database_closed)
 #0      SqfliteDatabaseMixin.checkNotClosed (package:sqflite_common/src/database_mixin.dart:457:7)
 #1      SqfliteDatabaseExecutorMixin.rawInsert (package:sqflite_common/src/database_mixin.dart:52:8)
 #2      SqfliteDatabaseExecutorMixin.insert (package:sqflite_common/src/database_mixin.dart:63:12)
 #3      User.saveLocalSession (package:prescore_flutter/util/user_util.dart:100:20)
 <asynchronous suspension>
 #4      User.telemetryLogin (package:prescore_flutter/util/user_util.dart:443:7)
 <asynchronous suspension>
```

**Comment by GoForceX** [comment]
但是至少无法复现了，那我就先 Close 了，有后续问题的话再 Reopen 也来得及（大概）

**Comment by GoForceX** [comment]
反转了，最新版仍然有……

**Comment by GoForceX** [comment]
> 啊，报什么错啊

效果与之前差不多，加载不出考试列表，显示未登录，刷新一次后恢复正常。

最怪的是新安装一段时间内不会有问题……

也导致我 debug 一直没法复现，release 安上没几天就寄了（

**Comment by GoForceX** [comment]
大约已修复，很久没碰到这个问题了。
